### ISSUE TITLE
MVP miscellaneous

### ISSUE THREAD

**Issue by wdower** [mitre/saf-site-frontend#258]
- [x] add favicon of the SAF logo (or determine if it's missing because of netlify hosting)
- [x] increase font size by one step globally
- [x] add a "©" to all references to MITRE SAF
- [x] add link to a SAF LICENSE.md file where we reference Apache2 license
- [x] add the logo for Open Source instead of the globe icon
- [x] change SAF shield logos to use real MITRE blue instead of the brighter blue from V1 of site
- [x] rename "refactr" vendor to "Sophos"
- [x] find out why "Adopted By The Community" is getting cut off underneath
- [x] links in User Stories are not highlighted
- [x] add card for OHDF to toolset (@wdower has the most current OHDF logo)
- [x] add go back button for FAQ
- [x] remove numbers from the titles of FAQ questions
- [x] allow content on training page to fill columns
- [x] rename beginner and advanced training courses to "InSpec Developer" and "Advanced InSpec Developer"
- [x] increase color variance in the rows of the library tables **{went with size increase instead}**
- [x] make sure FAQs are up to date
- [x] spell "open-source" consistently
- [x] change "Supports Capabilities" for toolset to be tool icons
- [x] Vulcan and Heimdall references should have copyright symbol

**Comment by wdower** [comment]
- [ ] On the homepage, the Validation Library card in the toolset cards is using the Hardening Library icon.  @ChrisHinchey

**Comment by ChrisHinchey** [comment]
@wdower Swapped it out for the correct logo

**Comment by ChrisHinchey** [comment]
Completed in #262
