### ISSUE TITLE
Inconsistent FAQ Routing

### ISSUE THREAD

**Issue by ChrisHinchey** [mitre/saf-site-frontend#39]
When navigating between FAQs in the netlify deployment the routing doesn't always go to the proper page.

**Comment by GavMason** [comment]
This issue may be solved by disabling intial caching (which is the Nuxt 3 default behavior for all data fetching methods).

useAsyncData("key", ()=> {}, { initialCache: false })

Here is an associated issue: https://github.com/nuxt/framework/discussions/5664
