### ISSUE TITLE
Linter Issues

### ISSUE THREAD

**Issue by GavMason** [mitre/saf-site-frontend#44]
- Main issue with linter is it flags all Nuxt content as errors/warnings. For now we have converted no-undef errors to warnings as they only are called on global Nuxt functions. There are Nuxt plugins however there was trouble getting them to work properly. 

- Addiontionally a warning is called using v-html as it rasies XSS security concerns. To render in the html in those use cases we must use v-html, therefore a way to address these concerns is to use a library to sanitize our html input. See https://stackoverflow.com/questions/46782359/vue-js-v-html-alternative

**Comment by ChrisHinchey** [comment]
Duplicate issue topic. Moved tasks to https://github.com/mitre/saf-site-frontend/issues/65
