### ISSUE TITLE
Add Visualize Page

### ISSUE THREAD

**Issue by wdower** [mitre/saf-site-frontend#50]
- Describe Heimdall (with a few screenshots, borrow from Heimdall's github page)
- Describe HDF converters (what they're for, namely allowing you to use other visualizers for data if desired)
- describe emasser

**Comment by wdower** [comment]
UPDATE: Discusions with stakeholders suggests that this page needs to be more about _the Visualize capability_ and less about _Heimdall in particular_.

- [ ] move the existing Visualize page to become the actual Heimdall product page
- [ ] on the Plan page, replace the Heimdall screenshots with icons vaguely describing the features of a good Visualization tool (can just be simple icons for now)
- [ ] add the Visualize icon above the header for this page and the phrase "![image](https://user-images.githubusercontent.com/57142072/222538798-8fb03d0c-097d-4201-b825-d3def84cf2cc.png)" as a subheader
- [ ] update the Lorem Ipsum paragraph to describe the Visualize capability generally

**Comment by ChrisHinchey** [comment]
Based on the updated tasks the foundation for visualize page has been completed and the text content for the page will be added in  #146 .
